lang_map_mm2l = {
    "af":"Afrikaans","am":"Amharic","ar":"Arabic","hy":"Armenian","as":"Assamese",
    "ast":"Asturian","az":"Azerbaijani","be":"Belarusian","bn":"Bengali","bs":"Bosnian",
    "bg":"Bulgarian","my":"Burmese","ca":"Catalan","ceb":"Cebuano","zh":"Chinese",
    "hr":"Croatian","cs":"Czech","da":"Danish","nl":"Dutch","en":"English",
    "et":"Estonian","tl":"Filipino","fi":"Finnish","fr":"French","ff":"Fulah",
    "gl":"Galician","lg":"Ganda","ka":"Georgian","de":"German","el":"Greek",
    "gu":"Gujarati","ha":"Hausa","he":"Hebrew","hi":"Hindi","hu":"Hungarian",
    "is":"Icelandic","ig":"Igbo","id":"Indonesian","ga":"Irish","it":"Italian",
    "ja":"Japanese","jv":"Javanese","kea":"Kabuverdianu","kam":"Kamba","kn":"Kannada",
    "kk":"Kazakh","km":"Khmer","ko":"Korean","ky":"Kyrgyz","lo":"Lao",
    "lv":"Latvian","ln":"Lingala","lt":"Lithuanian","luo":"Luo","lb":"Luxembourgish",
    "mk":"Macedonian","ms":"Malay","ml":"Malayalam","mt":"Maltese","mi":"Maori",
    "mr":"Marathi","mn":"Mongolian","ne":"Nepali","ns":"Northern Sotho","no":"Norwegian",
    "ny":"Nyanja","oc":"Occitan","or":"Oriya","om":"Oromo","ps":"Pashto",
    "fa":"Persian","pl":"Polish","pt":"Portuguese","pa":"Punjabi","ro":"Romanian",
    "ru":"Russian","sr":"Serbian","sn":"Shona","sd":"Sindhi","sk":"Slovak",
    "sl":"Slovenian","so":"Somali","ku":"Sorani Kurdish","es":"Spanish","sw":"Swahili",
    "sv":"Swedish","tg":"Tajik","ta":"Tamil","te":"Telugu","th":"Thai",
    "tr":"Turkish","uk":"Ukrainian","umb":"Umbundu","ur":"Urdu","uz":"Uzbek",
    "vi":"Vietnamese","cy":"Welsh","wo":"Wolof","xh":"Xhosa","yo":"Yoruba","zu":"Zulu"
}

lang_map_flores2mm = {
    "af":"afr","am":"amh","ar":"ara","hy":"hye","as":"asm",
    "ast":"ast","az":"azj","be":"bel","bn":"ben","bs":"bos",
    "bg":"bul","my":"mya","ca":"cat","ceb":"ceb","zh":"zho_simpl",
    "hr":"hrv","cs":"ces","da":"dan","nl":"nld","en":"eng",
    "et":"est","tl":"tgl","fi":"fin","fr":"fra","ff":"ful",
    "gl":"glg","lg":"lug","ka":"kat","de":"deu","el":"ell",
    "gu":"guj","ha":"hau","he":"heb","hi":"hin","hu":"hun",
    "is":"isl","ig":"ibo","id":"ind","ga":"gle","it":"ita",
    "ja":"jpn","jv":"jav","kea":"kea","kam":"kam","kn":"kan",
    "kk":"kaz","km":"khm","ko":"kor","ky":"kir","lo":"lao",
    "lv":"lav","ln":"lin","lt":"lit","luo":"luo","lb":"ltz",
    "mk":"mkd","ms":"msa","ml":"mal","mt":"mlt","mi":"mri",
    "mr":"mar","mn":"mon","ne":"npi","ns":"nso","no":"nob",
    "ny":"nya","oc":"oci","or":"ory","om":"orm","ps":"pus",
    "fa":"fas","pl":"pol","pt":"por","pa":"pan","ro":"ron",
    "ru":"rus","sr":"srp","sn":"sna","sd":"snd","sk":"slk",
    "sl":"slv","so":"som","ku":"ckb","es":"spa","sw":"swh",
    "sv":"swe","tg":"tgk","ta":"tam","te":"tel","th":"tha",
    "tr":"tur","uk":"ukr","umb":"umb","ur":"urd","uz":"uzb",
    "vi":"vie","cy":"cym","wo":"wol","xh":"xho","yo":"yor","zu":"zul"
}

langs_map_nllb = {
    "Afrikaans":"afr_Latn", "Amharic":"amh_Ethi", "Arabic":"arb_Arab", "Armenian":"hye_Armn", "Assamese":"asm_Beng",
    "Asturian":"ast_Latn", "Azerbaijani":"azj_Latn", "Belarusian":"bel_Cyrl", "Bengali":"ben_Beng", "Bosnian":"bos_Latn",
    "Bulgarian":"bul_Cyrl", "Burmese":"mya_Mymr", "Catalan":"cat_Latn", "Cebuano":"ceb_Latn", "Chinese":"zho_Hans",
    "Croatian":"hrv_Latn", "Czech":"ces_Latn", "Danish":"dan_Latn", "Dutch":"nld_Latn", "English":"eng_Latn",
    "Estonian":"est_Latn", "Filipino":"tgl_Latn", "Finnish":"fin_Latn", "French":"fra_Latn", "Fulah":"ful_Latn",
    "Galician":"glg_Latn", "Ganda":"lug_Latn", "Georgian":"kat_Geor", "German":"deu_Latn", "Greek":"ell_Grek",
    "Gujarati":"guj_Gujr", "Hausa":"hau_Latn", "Hebrew":"heb_Hebr", "Hindi":"hin_Deva", "Hungarian":"hun_Latn",
    "Icelandic":"isl_Latn", "Igbo":"ibo_Latn", "Indonesian":"ind_Latn", "Irish":"gle_Latn", "Italian":"ita_Latn",
    "Japanese":"jpn_Jpan", "Javanese":"jav_Latn", "Kabuverdianu":"kea_Latn", "Kamba":"kam_Latn", "Kannada":"kan_Knda",
    "Kazakh":"kaz_Cyrl", "Khmer":"khm_Khmr", "Korean":"kor_Hang", "Kyrgyz":"kir_Cyrl", "Lao":"lao_Laoo", "Latvian":"lav_Latn",
    "Lingala":"lin_Latn", "Lithuanian":"lit_Latn", "Luo":"luo_Latn", "Luxembourgish":"ltz_Latn", "Macedonian":"mkd_Cyrl",
    "Malay":"zsm_Latn", "Malayalam":"mal_Mlym", "Maltese":"mlt_Latn", "Maori":"mri_Latn", "Marathi":"mar_Deva",
    "Mongolian":"khk_Cyrl", "Nepali":"npi_Deva", "Northern Sotho":"nso_Latn", "Norwegian":"nob_Latn", "Nyanja":"nya_Latn",
    "Occitan":"oci_Latn", "Oriya":"ory_Orya", "Oromo":"gaz_Latn", "Pashto":"pbt_Arab", "Persian":"pes_Arab",
    "Polish":"pol_Latn", "Portuguese":"por_Latn", "Punjabi":"pan_Guru", "Romanian":"ron_Latn", "Russian":"rus_Cyrl",
    "Serbian":"srp_Cyrl", "Shona":"sna_Latn", "Sindhi":"snd_Arab", "Slovak":"slk_Latn", "Slovenian":"slv_Latn",
    "Somali":"som_Latn", "Sorani Kurdish":"ckb_Arab", "Spanish":"spa_Latn", "Swahili":"swh_Latn", "Swedish":"swe_Latn",
    "Tajik":"tgk_Cyrl", "Tamil":"tam_Taml", "Telugu":"tel_Telu", "Thai":"tha_Thai", "Turkish":"tur_Latn",
    "Ukrainian":"ukr_Cyrl", "Umbundu":"umb_Latn", "Urdu":"urd_Arab", "Uzbek":"uzn_Latn", "Vietnamese":"vie_Latn",
    "Welsh":"cym_Latn", "Wolof":"wol_Latn", "Xhosa":"xho_Latn", "Yoruba":"yor_Latn", "Zulu":"zul_Latn"
}
